apiVersion: v1
kind: Namespace
metadata:
  name: ingress-default-backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sorry-page
  namespace: ingress-default-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sorry-page
  template:
    metadata:
      labels:
        app: sorry-page
    spec:
      containers:
      - name: sorry-page-container
        image: sbeliakou/http-sorry-page
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: sorry-page-service
  namespace: ingress-default-backend
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: sorry-page