apiVersion: v1
kind: Pod
metadata:
  name: nginx-static
  namespace: static
  labels:
    app: nginx-static
spec:
  containers:
  - name: nginx
    image: nginx:alpine
    ports:
    - containerPort: 80