apiVersion: v1
kind: Pod
metadata:
  name: redis
  namespace: default
spec:
  containers:
  - name: redis
    image: redis:5-alpine
    # image: redis:123 # Intentional error

# RH7WGDBdaK3lRdSOxZQMsLaKS
# ixhh42HzObo5M1bPtI6XoD8M4