apiVersion: apps/v1
kind: Deployment
metadata:
  name: juan-app
  labels:
    task: deploy
    app: juan-app
    student: juan
spec:
  replicas: 1
  selector:
    matchLabels:
      deploy: juan-app
      kind: redis
      role: master
      tier: db
  template:
    metadata:
      labels:
        deploy: juan-app
        kind: redis
        role: master
        tier: db
    spec:
      initContainers:
        - name: init-container
          image: busybox:1.34
          command: ["sleep", "10"]
      containers:
        - name: redis-master
          image: redis:5-alpine
          ports:
            - containerPort: 6379
