apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"trouble-1-ingress","namespace":"default"},"spec":{"rules":[{"host":"trouble-1.k8slab.net","http":{"paths":[{"backend":{"service":{"name":"lime-svc","port":{"number":80}}},"path":"/lime","pathType":"ImplementationSpecific"},{"backend":{"service":{"name":"purple-svc","port":{"number":80}}},"path":"/purple","pathType":"ImplementationSpecific"}]}}]}}
  creationTimestamp: "2026-02-09T17:13:55Z"
  generation: 1
  name: trouble-1-ingress
  namespace: trouble-1
  resourceVersion: "33042"
  uid: a5d60dc5-1243-484a-833a-fc8b45fa43e0
spec:
  ingressClassName: nginx
  rules:
  - host: trouble-1.k8slab.net
    http:
      paths:
      - backend:
          service:
            name: lime-svc
            port:
              number: 80
        path: /lime
        pathType: ImplementationSpecific
      - backend:
          service:
            name: purple-svc
            port:
              number: 80
        path: /purple
        pathType: ImplementationSpecific
status:
  loadBalancer:
    ingress:
    - ip: 192.168.67.2
